Jaytee ramen
Snap-Engineering-Academy-2021/food-town pull request #27
Opened 2021-06-17 21:50 UTC by amriikk

init

2021-06-17 21:51 UTC, amriikk commented
update css

2021-06-17 22:26 UTC, sugarfig requested changes

2021-06-17 22:26 UTC, sugarfig commented on jaytee/index.html
> +            {Ingredients.map(name => <li key={name}> {name} </li>)}
prints out to screen. not sure if it was intended to do that.

2021-06-17 22:26 UTC, sugarfig commented on jaytee/js/script.js
> +const ingredients = ['1 tablespoon sesame oil', '3 teaspoons grated ginger', '4 teaspoons grated garlic', '4 cups broth', '4 cups water', '1 ounce dried shiitake mushrooms', '2 packages instant ramen
ingredients never get printed.

2021-06-21 22:11 UTC, amriikk commented
updated the broken code in html index

2021-06-21 22:17 UTC, sugarfig approved these changes
good job at fixing changes !

2021-06-21 22:17 UTC, merged