Guido paella recipe
Snap-Engineering-Academy-2021/food-town pull request #8
Opened 2021-06-16 22:21 UTC by guidoasbun

Hello Daniel, Please review my code

2021-06-16 22:46 UTC, Danieladd9 requested changes
so far I enjoyed taking a look at your code, I like some of fun things your adding to your webpage. I didn't find much of anything to critic in your code, so I guess keep going - keep up the good work!!

2021-06-16 22:46 UTC, Danieladd9 commented on guido/assets/js/script.js
> +
I the the small, medium, large function you've included.

2021-06-16 22:46 UTC, Danieladd9 commented on guido/assets/js/script.js
> +// Function NOT Complete
I see you still have not completed it, but I'm looking forward to seeing how it works after you done.

2021-06-16 22:46 UTC, Danieladd9 commented on guido/index.html
> +<!DOCTYPE html>
Index look 👍🏾

2021-06-16 22:46 UTC, Danieladd9 commented on guido/index.html
> +</html>
so far I enjoyed taking a look at your code, I like some of fun things your adding to your webpage. I didn't find much of anything to critic in your code, so I guess keep going - keep up the good work!!

2021-06-16 22:46 UTC, Danieladd9 approved these changes

2021-06-17 21:42 UTC, merged

2021-06-17 21:43 UTC, guidoasbun commented
All done!!